
input {
    kb_layout = us,ru
    kb_options = grp:alt_shift_toggle
}
bind = SUPER, B, exec, google-chrome-stable

# Экран с часами при включении ПК

# Служба связи с телефоном
exec-once = /usr/lib/kdeconnectd
exec-once = kdeconnect-indicator

# Прозрачность всех приложений и Chrome
windowrulev2 = opacity 0.88 0.78, class:^(google-chrome.*)$
windowrulev2 = opacity 0.88 0.78, class:.*

# Запуск экрана с часами строго при старте
bind = SUPER, P, exec, ~/.local/bin/phone
bind = $mainMod, T, exec, kitty

general {
    col.active_border = rgba(ffffffee) rgba(333333ee) 45deg
    col.inactive_border = rgba(1a1a1aa1)
}
exec-once = hyprlock

exec-once = caelestia shell lock lock
